### ISSUE TITLE
Geometry with TypedArray is not working

### ISSUE THREAD

**Issue by case2912** [GrimoireGL/grimoirejs-fundamental#75]
```js
const positions = new Float32Array(n)
const indices = new Uint16Array(n)
```

**Comment by cx20** [comment]
@case2912 The number of elements `n` does not exceed 65535?
If it is exceeded, WebGL extension must be enabled.
```js
var GLExtRequestor = gr.lib.fundamental.Resource.GLExtRequestor;
GLExtRequestor.request("OES_element_index_uint");
```

**Comment by kyasbal-1994** [comment]
@cx20 Thanks. But, this bug is already confirmed.
`Geometry.addAttribute` can be called with array. But, if users passed typed array into the method, Grimoire.js will use the argument simply.
It seems somehow the arguments being not passed to WebGL functions correctly.
This is truly bug.
